import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

export const PROPOSALS_TABLE_DESCRIPTION =
  "Candidate experience packages and turnkey itineraries generated by agents for human-in-the-loop review or silent tracking.";

export const PROPOSALS_COLUMN_DESCRIPTIONS: Record<string, string> = {
  id: "Unique proposal identifier.",
  goalId: "Referenced shopping goal ID.",
  dedupHash: "Unique hash derived from goal + entity + dates to avoid duplicate recommendations.",
  title: "Candidate proposal title.",
  description: "Detailed proposal narrative and highlight summary.",
  sourceUrl: "Original web link or ticket/flight listing URL.",
  imageUrl: "Image preview URL stored on Cloudflare Images or CDN.",
  cashPrice: "Cash price in USD.",
  pointsRequired: "Required award points if redeeming via points.",
  pointsProgram: "Name of the points program or transfer partner.",
  startDate: "Start date of event or travel.",
  endDate: "End date of event or travel.",
  location: "Destination city or venue.",
  itineraryPlan: "Structured turnkey day-by-day itinerary with transit directions, rest/nap slots, and adventure forks.",
  qualityScore: "Calculated quality/viability score (0-100).",
  uniquenessScore: "Calculated semantic uniqueness score (0-100).",
  status: "Lifecycle status: pending_triage, swiped_right, swiped_left, silent_tracking.",
  embedding: "Vector embedding array (e.g. 1536-dim or 768-dim) for semantic similarity matching.",
  createdAt: "Proposal discovery timestamp.",
};

export type TurnkeyItinerary = {
  legs: Array<{
    city: string;
    days: number;
    hotel: { name: string; why: string; transitWalkMinutes: number };
    activities: Array<{ time: string; name: string; transit: string; bookingUrl?: string }>;
    adventureForks: Array<{ title: string; description: string }>;
  }>;
};

export const proposals = sqliteTable("proposals", {
  id: text("id").primaryKey(),
  goalId: text("goal_id").notNull(),
  dedupHash: text("dedup_hash").unique().notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  sourceUrl: text("source_url").notNull(),
  imageUrl: text("image_url"),
  cashPrice: integer("cash_price"),
  pointsRequired: integer("points_required"),
  pointsProgram: text("points_program"),
  startDate: integer("start_date", { mode: "timestamp" }).notNull(),
  endDate: integer("end_date", { mode: "timestamp" }),
  location: text("location").notNull(),
  itineraryPlan: text("itinerary_plan", { mode: "json" }).$type<TurnkeyItinerary>(),
  qualityScore: integer("quality_score").notNull().default(80),
  uniquenessScore: integer("uniqueness_score").notNull().default(80),
  status: text("status", {
    enum: ["pending_triage", "swiped_right", "swiped_left", "silent_tracking"],
  })
    .default("pending_triage")
    .notNull(),
  embedding: text("embedding", { mode: "json" }).$type<number[]>(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
});

export const insertProposalSchema = createInsertSchema(proposals);
export const selectProposalSchema = createSelectSchema(proposals);
export type ProposalRow = typeof proposals.$inferSelect;
export type NewProposalRow = typeof proposals.$inferInsert;
